/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.pantallas;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.beans.DProveedor;
import modelo.beans.Pagos;
import modelo.beans.Pedidos;
import modelo.beans.RegistroCompra;
import modelo.datos.PagosDAO;

/**
 *
 * @author LuisCerv
 */
public class PPagos extends javax.swing.JPanel {

    /**
     * Creates new form PTiposUsuario
     */
    private final PagosDAO pdao;
    private Pagos p;
    private Pedidos ped;
    private boolean edit;
    private final String user; 
    private final String pwd;
    private int pagina=0;
    private int noPaginas=0;
    private int idPedidos=0;
    private int idProveedor=0;
    private int prodSelected=0;
    private double deuda;
    ArrayList<DProveedor> reg;
    /**
     * Creates new form PCategorias
     * @param user
     * @param pwd
     */
    public PPagos(String user, String pwd) {
        initComponents();
        this.user = user;
        this.pwd = pwd;
        pdao = new PagosDAO(user, pwd);
        p = new Pagos();
        noPaginas=pdao.cantPaginas();
        cargar();
        paginar();
        cForma.removeAllItems();
        cForma.addItem("Efectivo");
        cForma.addItem("Transaccion");
        cForma.addItem("Cheque");
        edit = false;
        this.tBusqueda.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
        this.tPedido.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
        this.tImporte.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)&&(caracter !='.')) {
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        bGuardar = new javax.swing.JButton();
        chkEstatus = new javax.swing.JCheckBox();
        bBuscar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tNumPage = new javax.swing.JLabel();
        bSiguiente = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bBuscar1 = new javax.swing.JButton();
        tImporte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cForma = new javax.swing.JComboBox<>();
        tPedido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        lAbonado = new javax.swing.JLabel();
        lDebe = new javax.swing.JLabel();

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idPago", "Fecha", "Importe", "Pedido", "Forma de Pago", "Cuenta proveedor", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDatos);

        bGuardar.setText("Realizar Pago");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        chkEstatus.setSelected(true);
        chkEstatus.setText("Estatus");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("importe");

        tNumPage.setText("0");

        bSiguiente.setText("Siguiente");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bBuscar1.setText("Buscar");
        bBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscar1ActionPerformed(evt);
            }
        });

        jLabel4.setText("idPedido");

        cForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Forma de pago");

        lTotal.setText("total");

        lAbonado.setText("abono");

        lDebe.setText("deuda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(cForma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tPedido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 117, Short.MAX_VALUE)
                                        .addComponent(chkEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bEliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(170, 170, 170)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lAbonado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lDebe, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNumPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lDebe)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bBuscar1)
                            .addComponent(jLabel4)
                            .addComponent(tPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAbonado)
                            .addComponent(tImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEliminar)
                            .addComponent(bEditar)
                            .addComponent(bBuscar)
                            .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkEstatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(bGuardar)
                        .addGap(17, 17, 17)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNumPage)
                    .addComponent(bSiguiente)
                    .addComponent(bAtras))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        if (this.tPedido.getText().equals("") || this.tImporte.getText().equals("")) {
            JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda", "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        } else {
            double pago=Double.parseDouble(this.tImporte.getText());
            if (deuda>=pago) {
                p = new Pagos();
                p.setIdPago(pdao.UltimoIDPagos());
                p.setFecha("getdate()");
                p.setImporte(pago);
                p.setIdPedido(ped.getIdPedido());
                p.setIdFormaPago(this.cForma.getSelectedIndex());
                p.setIdCuentaProveedor(ped.getIdProveedor());
                p.setEstatus("A");
                pdao.guardarPagos(p);
                pdao.actualizarTotalPedido(ped.getIdPedido());ped=pdao.buscarPedido(Integer.parseInt(this.tPedido.getText()));
                this.lTotal.setText("El monto total es: "+ped.getTotalPagar());
                this.lAbonado.setText("Usted ha pagado:  "+ped.getCantidadPagada());
                deuda=ped.getTotalPagar()-ped.getCantidadPagada();
                this.lDebe.setText("Usted debe:      "+deuda);
            } else {
                JOptionPane.showConfirmDialog(this, "No puede abonar mas de la cantidad adeudada", "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
            cargar();
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        if(this.tBusqueda.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda","Error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        } else {
            this.tDatos.setModel(pdao.cargarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        if (edit) {
            if(this.tImporte.getText().equals("")||this.tPedido.getText().equals("")){
                JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda","Error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
            }else{
                edit = false;
                p.setIdPedido(idPedidos);
                p.setImporte(Double.parseDouble(this.tImporte.getText()));
                if (this.chkEstatus.isSelected()) {
                    p.setEstatus("A");
                } else {
                    p.setEstatus("I");
                }
                pdao.editarPagos(p, p.getIdPago());
                cargar();
            }
        } else {
            edit = true;
            this.tBusqueda.setEnabled(!edit);
            this.tDatos.setModel(pdao.cargarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
            p = pdao.buscarIdEdicion(Integer.parseInt(this.tBusqueda.getText()));
            this.tPedido.setText(String.valueOf(p.getIdPedido()));
            this.tImporte.setText(p.getImporte()+"");
            if (p.getEstatus().equals("A")) {
                this.chkEstatus.setSelected(true);
            } else {
                this.chkEstatus.setSelected(false);
            }
            this.cForma.setSelectedIndex(ped.getIdProveedor());
        }
        this.bBuscar.setVisible(!edit);
        this.bEliminar.setVisible(!edit);
        this.bGuardar.setVisible(!edit);
    }//GEN-LAST:event_bEditarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        if(this.tBusqueda.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda","Error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        } else {
            p = pdao.buscarIdEdicion(Integer.parseInt(this.tBusqueda.getText()));
            pdao.eliminarPagos(Integer.parseInt(this.tBusqueda.getText()));
            cargar();
            Limpiar();
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        // TODO add your handling code here:
        if(pagina<noPaginas)pagina++;
        paginar();
        cargar();
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        if(pagina>0)pagina--;
        paginar();
        cargar();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscar1ActionPerformed
        if(this.tPedido.getText().equals("")){
            JOptionPane.showConfirmDialog(this,"Necesita introducir el identificador de un pedido","Error de pago",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        }else{
            ped=pdao.buscarPedido(Integer.parseInt(this.tPedido.getText()));
            if(ped.getEstatus().equals("T")||ped.getEstatus().equals("P")||ped.getEstatus().equals("R")){
                this.lTotal.setText("El monto total es: "+ped.getTotalPagar());
                this.lAbonado.setText("Usted ha pagado:  "+ped.getCantidadPagada());
                deuda=ped.getTotalPagar()-ped.getCantidadPagada();
                this.lDebe.setText("Usted debe:      "+deuda);
            }else{
                JOptionPane.showConfirmDialog(this,"Aun no se puede abonar un pago a este pedido","Error de pago",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bBuscar1ActionPerformed
    public void cargar() {
        reg=new ArrayList();
        reg=pdao.buscarProveedores();
        this.tDatos.setModel(pdao.cargarTabla(tDatos,pagina));
        this.repaint();
    }
//    private int buscarPr(int id){
//    int idx=-1;
//    for (int i = 0; i < reg.size(); i++) {
//        if(reg.get(i).getIdPresentacion()==id)return i;
//    }
//    return idx;
//}
    public void paginar(){
        if(pagina==0){
            this.bAtras.setVisible(false);
        }else{
            this.bAtras.setVisible(true);
        }
        if(pagina<noPaginas){
            this.bSiguiente.setVisible(true);
        }else{
            this.bSiguiente.setVisible(false);
        }
        this.tNumPage.setText((pagina+1)+" de "+(noPaginas+1));
    }
    public void Limpiar() {
        this.tImporte.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bBuscar1;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JComboBox<String> cForma;
    private javax.swing.JCheckBox chkEstatus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAbonado;
    private javax.swing.JLabel lDebe;
    private javax.swing.JLabel lTotal;
    private javax.swing.JTextField tBusqueda;
    private javax.swing.JTable tDatos;
    private javax.swing.JTextField tImporte;
    private javax.swing.JLabel tNumPage;
    private javax.swing.JTextField tPedido;
    // End of variables declaration//GEN-END:variables
}
