/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this tplate file, choose Tools | Tplates
 * and open the tplate in the editor.
 */
package modelo.pantallas;
import daltonik_erp.Archivos;
import daltonik_erp.Excel;
import java.io.IOException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.beans.DProveedor;
import modelo.beans.DSucursal;
import modelo.beans.Pedidos;
import modelo.datos.PedidosDAO;
/**
 *
 * @author Nadia Cross
 */
public class PPedidos extends javax.swing.JPanel {
    private final PedidosDAO pdao;
    private Pedidos p;
    private boolean edit;
    private final String user; 
    private final String pwd;
    private int pagina=0;
    private int noPaginas=0;
    private int idPedidos=0;
    private int idProveedor=0;
    private int proSelected=0;
    private int idSucursal=0;
    private int suSelected=0;
    ArrayList<DProveedor> reg;
    ArrayList<DSucursal> regS;
    /**
     * Creates new form PPedidos
     */
    public PPedidos(String user, String pwd) {
        initComponents();
        this.user = user;
        this.pwd = pwd;
        pdao = new PedidosDAO(user, pwd);
        p = new Pedidos();
        noPaginas=pdao.cantPaginas();
        cargar();
        paginar();
        edit = false;
        
        
        this.tBusqueda.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
        this.tRecepcion.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)&&(caracter!='-')) {
                    e.consume();
                }
            }
        });
        this.tRegistro.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)&& (caracter!='-'))  {
                    e.consume();
                }
            }
        });
        this.tEmpleado.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bEliminar = new javax.swing.JButton();
        chkEstatus = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tRegistro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNumPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        bSiguiente = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        tRecepcion = new javax.swing.JTextField();
        tBusqueda = new javax.swing.JTextField();
        tMensajes = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        tEmpleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cProveedor = new javax.swing.JComboBox<>();
        cSucursal = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        chkEstatus.setText("Activar");
        chkEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstatusActionPerformed(evt);
            }
        });

        jLabel2.setText("idPedido");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha de recepcion");

        tRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRegistroActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Sucursal");

        jLabel6.setText("Fecha de registro");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Proveedor");

        tNumPage.setText("0");

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idPedido", "Fecha Registro", "Fecha Recepción", "Total a Pagar", "Cantidad Pagada", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDatos);

        bSiguiente.setText("Siguiente");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bGuardar.setText("Generar orden");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        tRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRecepcionActionPerformed(evt);
            }
        });

        tMensajes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Empleado");

        cProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cProveedorItemStateChanged(evt);
            }
        });
        cProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProveedorActionPerformed(evt);
            }
        });

        cSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cSucursal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cSucursalItemStateChanged(evt);
            }
        });

        jButton1.setText("Generar Reporte de Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(tRecepcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tRegistro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tEmpleado)
                            .addComponent(cProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNumPage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSiguiente)
                                .addGap(170, 170, 170))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(chkEstatus)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bEliminar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEditar)
                            .addComponent(bBuscar))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(bEliminar)
                            .addComponent(chkEstatus))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNumPage)
                    .addComponent(bSiguiente)
                    .addComponent(bAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(this, "Estas seguro de que deseas borrar este registro?", "Alerta",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(x==JOptionPane.YES_OPTION){
            pdao.eliminarPedidos(Integer.parseInt(this.tBusqueda.getText()));
            noPaginas=pdao.cantPaginas();
        }        
        cargar();
        paginar();
        limpiar();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void chkEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstatusActionPerformed

    private void tRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRegistroActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        // TODO add your handling code here:
        if(pagina<noPaginas)pagina++;
        paginar();
        cargar();
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        if(pagina>0)pagina--;
        paginar();
        cargar();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        boolean fechReg = false;
        boolean fechRec = false;
        boolean prov = false;
        boolean idSuc = false;
        boolean idEmp = false;
        if (this.tRegistro.getText().equals("") || this.tRecepcion.getText().equals("")|| this.tEmpleado.getText().equals("")) {
            JOptionPane.showConfirmDialog(this, "Hay un error, favor de verificar","error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        } else {
            fechReg = true;
            if (this.tRegistro.getText().length() != 10) {
                JOptionPane.showMessageDialog(tRegistro, "No es válido, hacen falta dígitos");
            } else {
                fechRec = true;
            }
            p = new Pedidos();
            idPedidos = pdao.UltimoIDPedidos();
            idProveedor = reg.get(proSelected).getIdProveedor();
            idSucursal = regS.get(suSelected).getIdSucursal();
            p.setIdPedido(idPedidos);
            p.setFechaRegistro(this.tRegistro.getText());
            p.setFechaRecepcion(this.tRecepcion.getText());
            p.setTotalPagar(0);
            p.setCantidadPagada(0);
            p.setEstatus("A");
            p.setIdProveedor(idProveedor);
            p.setIdSucursal(idSucursal);
            p.setIdEmpleado(Integer.parseInt(this.tEmpleado.getText()));
            pdao.guardarPedidos(p);
            noPaginas = pdao.cantPaginas();
            cargar();
            paginar();
            limpiar();
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        if (this.tBusqueda.getText().equals("")) {
            JOptionPane.showConfirmDialog(this, "necesita introducir el id del pedido para realizar la busqueda", "error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        } else {
            this.tDatos.setModel(pdao.buscarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
            limpiar();
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        if(this.tBusqueda.getText().equals("")){
            JOptionPane.showConfirmDialog(this,"necesita introducir el id del pedido para realizar la busqueda","error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        }else{
        if (edit) {
            edit = false;
            this.tBusqueda.setEnabled(!edit);
            p = new Pedidos();
            idPedidos = pdao.UltimoIDPedidos();
            idProveedor = reg.get(proSelected).getIdProveedor();
            idSucursal = regS.get(suSelected).getIdSucursal();
            p.setIdPedido(Integer.parseInt(this.tBusqueda.getText()));
            p.setFechaRegistro(this.tRegistro.getText());
            p.setFechaRecepcion(this.tRecepcion.getText());
            p.setTotalPagar(0);
            p.setCantidadPagada(0);
            p.setEstatus("A");
            p.setIdProveedor(idProveedor);
            p.setIdSucursal(idSucursal);
            p.setIdEmpleado(Integer.parseInt(this.tEmpleado.getText()));
            if (this.chkEstatus.isSelected()) {
                p.setEstatus("A");
            } else {
                p.setEstatus("I");
            }
            pdao.editarPedidos(p, p.getIdPedido());
            noPaginas = pdao.cantPaginas();
            cargar();
            paginar();
            limpiar();
        } else {
            edit = true;
            this.tBusqueda.setEnabled(!edit);
            this.tDatos.setModel(pdao.buscarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
            p = pdao.buscarIdEdicion(Integer.parseInt(this.tBusqueda.getText()));
            this.tRegistro.setText(String.valueOf(p.getFechaRegistro()));
            this.tRecepcion.setText(String.valueOf(p.getFechaRecepcion()));
            this.tEmpleado.setText(String.valueOf(p.getIdEmpleado()));
            this.cProveedor.setSelectedIndex(this.buscarPr(p.getIdProveedor()));
            this.cSucursal.setSelectedIndex(this.buscarSu(p.getIdSucursal()));
            if (p.getEstatus().equals("A")) {
                this.chkEstatus.setSelected(true);
            } else {
                this.chkEstatus.setSelected(false);
            }                        
                }
        this.bBuscar.setVisible(!edit);
        this.bEliminar.setVisible(!edit);
        this.bGuardar.setVisible(!edit);
        }
    }//GEN-LAST:event_bEditarActionPerformed

    private void tRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRecepcionActionPerformed

    private void cProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cProveedorActionPerformed

    private void cProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cProveedorItemStateChanged
        // TODO add your handling code here:
        proSelected=this.cProveedor.getSelectedIndex();
        
    }//GEN-LAST:event_cProveedorItemStateChanged

    private void cSucursalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cSucursalItemStateChanged
        // TODO add your handling code here:
        suSelected=this.cSucursal.getSelectedIndex();
    }//GEN-LAST:event_cSucursalItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.tMensajes.setText("Generando reporte");
        String ruta="";
        String fecha="";
        String con;
        Archivos arc=new Archivos();
        con=JOptionPane.showInputDialog(this, "Introduzca el nombre del archivo", "Reporte Excel", JOptionPane.WARNING_MESSAGE);
        try{
            Date sistFecha=new Date();
            SimpleDateFormat formato=new SimpleDateFormat("dd MMMMM YYYY");
            fecha=formato.format(sistFecha);
            ruta=arc.cargarConfig()+con+fecha+".xlsx";
            Excel ex=new Excel(ruta);
            ex.crearExcel();
            ex.modificar();
            this.tMensajes.setText("Reporte "+ruta+ " se ha creado");
        }catch(NullPointerException e){
            this.tMensajes.setText(e.getMessage());
        } catch (IOException ex) {
            this.tMensajes.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
private int buscarPr(int id){
    int idx=-1;
    for (int i = 0; i < reg.size(); i++) {
        if(reg.get(i).getIdProveedor()==id)return i;
    }
    return idx;
}
private int buscarSu(int id){
    int idx=-1;
    for (int i = 0; i < regS.size(); i++) {
        if(regS.get(i).getIdSucursal()==id)return i;
    }
    return idx;
}
   
    public void cargar() {
        this.tDatos.setModel(pdao.cargarTabla(tDatos,pagina));
        reg=new ArrayList();
        reg=pdao.buscarProveedores();
        cProveedor.removeAllItems();
        for (int i = 0; i < reg.size(); i++) {
            this.cProveedor.addItem(reg.get(i).getNombre());
        }
        regS=new ArrayList();
        regS=pdao.buscarSucursales();
        cSucursal.removeAllItems();
        for (int i = 0; i < regS.size(); i++) {
            this.cSucursal.addItem(regS.get(i).getNombre());
        }
        this.repaint();
    }
    
    public void paginar(){
        if(pagina==0){
            this.bAtras.setVisible(false);
        }else{
            this.bAtras.setVisible(true);
        }
        if(pagina<noPaginas){
            this.bSiguiente.setVisible(true);
        }else{
            this.bSiguiente.setVisible(false);
        }
        this.tNumPage.setText((pagina+1)+" de "+(noPaginas+1));
    }
    
    public void limpiar() {
        this.tBusqueda.setText("");        
        this.tRecepcion.setText("");
        this.tRegistro.setText("");
        this.tEmpleado.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JComboBox<String> cProveedor;
    private javax.swing.JComboBox<String> cSucursal;
    private javax.swing.JCheckBox chkEstatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBusqueda;
    private javax.swing.JTable tDatos;
    private javax.swing.JTextField tEmpleado;
    private javax.swing.JLabel tMensajes;
    private javax.swing.JLabel tNumPage;
    private javax.swing.JTextField tRecepcion;
    private javax.swing.JTextField tRegistro;
    // End of variables declaration//GEN-END:variables
}
