/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.pantallas;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.beans.PedidoDetalle;
import modelo.beans.RegistroCompra;
import modelo.datos.PedidoDetalleDAO;

/**
 *
 * @author LuisCerv
 */
public class PPedidoDetalle extends javax.swing.JPanel {

    /**
     * Creates new form PTiposUsuario
     */
    private final PedidoDetalleDAO pdao;
    private PedidoDetalle p;
    private boolean edit;
    private final String user; 
    private final String pwd;
    private int pagina=0;
    private int noPaginas=0;
    private int idPedidos=0;
    private int idProveedor=0;
    private int prodSelected=0;
    ArrayList<RegistroCompra> reg;
    /**
     * Creates new form PCategorias
     * @param user
     * @param pwd
     */
    public PPedidoDetalle(String user, String pwd) {
        initComponents();
        this.user = user;
        this.pwd = pwd;
        pdao = new PedidoDetalleDAO(user, pwd);
        p = new PedidoDetalle();
        noPaginas=pdao.cantPaginas();
        cargar();
        paginar();
        edit = false;
        this.tIdPedido.setText(idPedidos+"");
        this.tBusqueda.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
        this.tIdPedido.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
        this.tCantidad.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        bGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tIdPedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chkEstatus = new javax.swing.JCheckBox();
        bBuscar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        tCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tNumPage = new javax.swing.JLabel();
        bSiguiente = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        CProducto = new javax.swing.JComboBox<>();
        bBuscar1 = new javax.swing.JButton();

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idPedidoDetalle", "Cant Pedida", "Precio Compra", "subtotal", "idPedido", "id Presentacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDatos);

        bGuardar.setText("Agregar elemento");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("idPedido");

        jLabel1.setText("Producto");

        chkEstatus.setSelected(true);
        chkEstatus.setText("Estatus");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad");

        tNumPage.setText("0");

        bSiguiente.setText("Siguiente");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        CProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CProductoItemStateChanged(evt);
            }
        });

        bBuscar1.setText("Buscar");
        bBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tIdPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(tCantidad)
                            .addComponent(CProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 130, Short.MAX_VALUE)
                                .addComponent(chkEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNumPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEliminar)
                            .addComponent(bEditar)
                            .addComponent(bBuscar)
                            .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkEstatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bGuardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNumPage)
                    .addComponent(bSiguiente)
                    .addComponent(bAtras))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        if (this.tCantidad.getText().equals("") || this.tIdPedido.getText().equals("")) {
            JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda", "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        } else {
            p = new PedidoDetalle();
            p.setIdPedidoDetalle(pdao.UltimoIDPedidoDetalle());
            p.setCantidadPedida(Integer.parseInt(this.tCantidad.getText()));
            p.setPrecioCompra(this.reg.get(prodSelected).getPrecio());
            p.setSubtotal(Integer.parseInt(this.tCantidad.getText()) * this.reg.get(prodSelected).getPrecio());
            p.setCantRecibida(0);
            p.setCantRechazada(0);
            p.setCantAceptada(0);
            p.setIdPedido(idPedidos);
            int x = this.reg.get(prodSelected).getIdPresentacion();
            p.setIdPresentacion(x);
            p.setEstatus("A");
            pdao.guardarPedidoDetalle(p);
            pdao.actualizarTotalPedido(idPedidos);
            this.tDatos.setModel(pdao.buscarId(tDatos, Integer.parseInt(this.tIdPedido.getText())));
            cargar();
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        if(this.tBusqueda.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda","Error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        } else {
            this.tDatos.setModel(pdao.cargarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        if (edit) {
            if(this.tCantidad.getText().equals("")||this.tIdPedido.getText().equals("")){
                JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda","Error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
            }else{
                edit = false;
                this.tBusqueda.setEnabled(!edit);
                this.tIdPedido.setEnabled(!edit);
                p.setIdPedidoDetalle(Integer.parseInt(this.tBusqueda.getText()));
                p.setCantidadPedida(Integer.parseInt(this.tCantidad.getText()));
                p.setPrecioCompra(this.reg.get(prodSelected).getPrecio());
                p.setSubtotal(Integer.parseInt(this.tCantidad.getText()) * this.reg.get(prodSelected).getPrecio());
                p.setCantRecibida(0);
                p.setCantRechazada(0);
                p.setCantAceptada(0);
                p.setIdPedido(idPedidos);
                if (this.chkEstatus.isSelected()) {
                    p.setEstatus("A");
                } else {
                    p.setEstatus("I");
                }
                pdao.editarPedidoDetalle(p, p.getIdPedidoDetalle());
                pdao.actualizarTotalPedido(idPedidos);
                this.tDatos.setModel(pdao.buscarId(tDatos, Integer.parseInt(this.tIdPedido.getText())));
                cargar();
            }
        } else {
            edit = true;
            this.tBusqueda.setEnabled(!edit);
            this.tDatos.setModel(pdao.cargarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
            p = pdao.buscarIdEdicion(Integer.parseInt(this.tBusqueda.getText()));
            this.tIdPedido.setText(String.valueOf(p.getIdPedido()));
            this.idProveedor=pdao.ProveedorPedido(Integer.parseInt(this.tIdPedido.getText()));
            cargar();
            this.tCantidad.setText(p.getCantidadPedida()+"");
            this.tIdPedido.setEnabled(!edit);
            if (p.getEstatus().equals("A")) {
                this.chkEstatus.setSelected(true);
            } else {
                this.chkEstatus.setSelected(false);
            }
            this.CProducto.setSelectedIndex(this.buscarPr(p.getIdPresentacion()));
        }
        this.bBuscar.setVisible(!edit);
        this.bEliminar.setVisible(!edit);
        this.bGuardar.setVisible(!edit);
    }//GEN-LAST:event_bEditarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        if(this.tBusqueda.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda","Error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        } else {
            p = pdao.buscarIdEdicion(Integer.parseInt(this.tBusqueda.getText()));
            this.tIdPedido.setText(String.valueOf(p.getIdPedido()));
            pdao.eliminarPedidoDetalle(Integer.parseInt(this.tBusqueda.getText()));
            pdao.actualizarTotalPedido(idPedidos);
            cargar();
            Limpiar();
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        // TODO add your handling code here:
        if(pagina<noPaginas)pagina++;
        paginar();
        cargar();
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        if(pagina>0)pagina--;
        paginar();
        cargar();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void CProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CProductoItemStateChanged
        prodSelected=this.CProducto.getSelectedIndex();
    }//GEN-LAST:event_CProductoItemStateChanged

    private void bBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscar1ActionPerformed
        if(this.tIdPedido.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Necesita ingresar un valor de busqueda","Error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        } else {
            this.tDatos.setModel(pdao.buscarId(tDatos, Integer.parseInt(this.tIdPedido.getText())));
            this.idProveedor = pdao.ProveedorPedido(Integer.parseInt(this.tIdPedido.getText()));
            this.idPedidos = Integer.parseInt(this.tIdPedido.getText());
            cargar();
        }
    }//GEN-LAST:event_bBuscar1ActionPerformed
    public void cargar() {
        reg=new ArrayList();
        reg=pdao.buscarProductosProveedor(idProveedor);
        CProducto.removeAllItems();
        for (int i = 0; i < reg.size(); i++) {
            this.CProducto.addItem(reg.get(i).getNombre());
        }
        this.repaint();
    }
    private int buscarPr(int id){
    int idx=-1;
    for (int i = 0; i < reg.size(); i++) {
        if(reg.get(i).getIdPresentacion()==id)return i;
    }
    return idx;
}
    public void paginar(){
        if(pagina==0){
            this.bAtras.setVisible(false);
        }else{
            this.bAtras.setVisible(true);
        }
        if(pagina<noPaginas){
            this.bSiguiente.setVisible(true);
        }else{
            this.bSiguiente.setVisible(false);
        }
        this.tNumPage.setText((pagina+1)+" de "+(noPaginas+1));
    }
    public void Limpiar() {
        this.tCantidad.setText("");
        this.tIdPedido.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CProducto;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bBuscar1;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JCheckBox chkEstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBusqueda;
    private javax.swing.JTextField tCantidad;
    private javax.swing.JTable tDatos;
    private javax.swing.JTextField tIdPedido;
    private javax.swing.JLabel tNumPage;
    // End of variables declaration//GEN-END:variables
}
