/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.pantallas;
import java.util.ArrayList;
import modelo.beans.DProveedor;
import modelo.beans.Pedidos;
import modelo.beans.RegistroCompra;
import modelo.datos.PedidosDAO;
/**
 *
 * @author Nadia Cross
 */
public class PPedidos extends javax.swing.JPanel {
    private final PedidosDAO pdao;
    private Pedidos p;
    private boolean edit;
    private final String user; 
    private final String pwd;
    private int pagina=0;
    private int noPaginas=0;
    private int idPedidos=0;
    private int idProveedor=0;
    private int proSelected=0;
    ArrayList<DProveedor> reg;
    /**
     * Creates new form PPedidos
     */
    public PPedidos(String user, String pwd) {
        initComponents();
        this.user = user;
        this.pwd = pwd;
        pdao = new PedidosDAO(user, pwd);
        p = new Pedidos();
        noPaginas=pdao.cantPaginas();
        cargar();
        paginar();
        edit = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tSucursal = new javax.swing.JTextField();
        bEliminar = new javax.swing.JButton();
        chkEstatus = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tRegistro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNumPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        bSiguiente = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        tRecepcion = new javax.swing.JTextField();
        tBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        tEmpleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cProveedor = new javax.swing.JComboBox<>();

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        chkEstatus.setText("Activar");
        chkEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstatusActionPerformed(evt);
            }
        });

        jLabel2.setText("idPedido");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha de recepcion");

        tRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRegistroActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Sucursal");

        jLabel6.setText("Fecha de registro");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Proveedor");

        tNumPage.setText("0");

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idEmpaque", "Nombre", "Capacidad", "Estatus", "idUnidadMedida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDatos);

        bSiguiente.setText("Siguiente");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bGuardar.setText("Generar orden");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        tRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRecepcionActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Empleado");

        cProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cProveedorItemStateChanged(evt);
            }
        });
        cProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(tSucursal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tRecepcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tRegistro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tEmpleado)
                            .addComponent(cProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNumPage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSiguiente)
                                .addGap(170, 170, 170))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(chkEstatus))
                            .addComponent(bBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bEliminar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bGuardar)
                .addGap(18, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEditar)
                            .addComponent(bBuscar))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(bEliminar)
                        .addComponent(chkEstatus)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNumPage)
                    .addComponent(bSiguiente)
                    .addComponent(bAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        pdao.eliminarPedidos(Integer.parseInt(this.tBusqueda.getText()));
        noPaginas=pdao.cantPaginas();
        cargar();
        paginar();
        limpiar();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void chkEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstatusActionPerformed

    private void tRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRegistroActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        // TODO add your handling code here:
        if(pagina<noPaginas)pagina++;
        paginar();
        cargar();
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        if(pagina>0)pagina--;
        paginar();
        cargar();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        p=new Pedidos();
        idPedidos=pdao.UltimoIDPedidos();
        idProveedor=reg.get(proSelected).getIdProveedor();
        p.setIdPedido(idPedidos);
        p.setFechaRegistro(this.tRegistro.getText());
        p.setFechaRecepcion(this.tRecepcion.getText());
        p.setTotalPagar(0);
        p.setCantidadPagada(0);
        p.setEstatus("A");
        p.setIdProveedor(idProveedor);
        p.setIdSucursal(Integer.parseInt(this.tSucursal.getText()));
        p.setIdEmpleado(Integer.parseInt(this.tEmpleado.getText()));
        pdao.guardarPedidos(p);
        noPaginas=pdao.cantPaginas();
        cargar();
        paginar();
        limpiar();
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        this.tDatos.setModel(pdao.buscarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
        limpiar();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
//        if(edit) {
//            edit=false;
//            p = new Empaque();
//            emp.setIdUnidad(Integer.parseInt(this.tBusqueda.getText()));
//            emp.setCapacidad(Double.parseDouble(this.tCapacidad.getText()));
//            emp.setNombre(this.tRecepcion.getText());
//            emp.setIdUnidad(Integer.parseInt(this.tSucursal.getText()));
//            if (this.chkEstatus.isSelected()) {
//                emp.setEstatus("A");
//            } else {
//                emp.setEstatus("I");
//            }
//            edao.editarEmpaque(emp, emp.getIdEmpaque());
//            noPaginas=edao.cantPaginas();
//            cargar();
//            paginar();
//            limpiar();
//        }else{
//            edit=true;
//            this.tDatos.setModel(edao.buscarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
//            emp = edao.buscarIdEdicion(Integer.parseInt(this.tBusqueda.getText()));
//            this.tRecepcion.setText(emp.getNombre());
//            this.tCapacidad.setText(String.valueOf(emp.getCapacidad()));
//            this.tSucursal.setText(String.valueOf(emp.getIdUnidad()));
//            if (emp.getEstatus().equals("A")) {
//                this.chkEstatus.setSelected(true);
//            } else {
//                this.chkEstatus.setSelected(false);
//            }
//        }
//        this.bBuscar.setVisible(!edit);
//        this.bEliminar.setVisible(!edit);
//        this.bGuardar.setVisible(!edit);
    }//GEN-LAST:event_bEditarActionPerformed

    private void tRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRecepcionActionPerformed

    private void cProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cProveedorActionPerformed

    private void cProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cProveedorItemStateChanged
        // TODO add your handling code here:
        proSelected=this.cProveedor.getSelectedIndex();
        
    }//GEN-LAST:event_cProveedorItemStateChanged
public void cargar() {
        this.tDatos.setModel(pdao.cargarTabla(tDatos,pagina));
        reg=new ArrayList();
        reg=pdao.buscarProveedores();
        cProveedor.removeAllItems();
        for (int i = 0; i < reg.size(); i++) {
            this.cProveedor.addItem(reg.get(i).getNombre());
        }
        this.repaint();
    }
    
    public void paginar(){
        if(pagina==0){
            this.bAtras.setVisible(false);
        }else{
            this.bAtras.setVisible(true);
        }
        if(pagina<noPaginas){
            this.bSiguiente.setVisible(true);
        }else{
            this.bSiguiente.setVisible(false);
        }
        this.tNumPage.setText((pagina+1)+" de "+(noPaginas+1));
    }
    
    public void limpiar() {
        this.tBusqueda.setText("");
        this.tEmpleado.setText("");
        this.tRecepcion.setText("");
        this.tRegistro.setText("");
        this.tSucursal.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JComboBox<String> cProveedor;
    private javax.swing.JCheckBox chkEstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBusqueda;
    private javax.swing.JTable tDatos;
    private javax.swing.JTextField tEmpleado;
    private javax.swing.JLabel tNumPage;
    private javax.swing.JTextField tRecepcion;
    private javax.swing.JTextField tRegistro;
    private javax.swing.JTextField tSucursal;
    // End of variables declaration//GEN-END:variables
}
