/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.pantallas;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.beans.ConsultaEmpaque;
import modelo.beans.ConsultaProductos;
import modelo.datos.EmpaqueDAO;
import modelo.beans.Empaque;
import modelo.beans.PresentacionesProducto;
import modelo.datos.PresentacionesProductoDAO;

/**
 *
 * @author Francisco Figueroa
 */
public class PPresentacionesProducto extends javax.swing.JPanel {

    private PresentacionesProductoDAO pdao;
    private PresentacionesProducto pr;
    private boolean edit;
    private String user;
    private String pwd;
    private int pagina = 0;
    private int noPaginas = 0;
    private int idProveedor=0;
    private int proSelected=0;
    ArrayList<ConsultaProductos> reg;
    private int idEmpaque=0;
    private int EmpSelected=0;
    ArrayList<ConsultaEmpaque> regE;

    public PPresentacionesProducto(String user, String pwd) {
        initComponents();
        this.user = user;
        this.pwd = pwd;
        edit = false;
        pdao = new PresentacionesProductoDAO(user, pwd);
        pr = new PresentacionesProducto();
        noPaginas = pdao.cantPaginas();
        cargar();
        paginar();
        this.tBusqueda.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
        this.tPuntoReorden.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
        this.tPrecioVenta.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE) && (caracter != '.')) {
                    e.consume();
                }
            }
        });
        this.tPrecioCompra.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != KeyEvent.VK_BACK_SPACE) && (caracter != '.')) {
                    e.consume();
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPrecioCompra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tPrecioVenta = new javax.swing.JTextField();
        tPuntoReorden = new javax.swing.JTextField();
        chkEstatus = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        bGuardar = new javax.swing.JButton();
        tBusqueda = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bAtras = new javax.swing.JButton();
        tNumPage = new javax.swing.JLabel();
        bSiguiente = new javax.swing.JButton();
        cProductos = new javax.swing.JComboBox<>();
        cEmpaque = new javax.swing.JComboBox<>();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        tPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecioVentaActionPerformed(evt);
            }
        });
        tPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tPrecioVentaKeyTyped(evt);
            }
        });

        chkEstatus.setText("Activar");
        chkEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstatusActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("PrecioCompra:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("puntoReorden:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PrecioVenta:");

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idPresentacion", "PrecioCompra", "PrecioVenta", "puntoReorden", "idProducto", "idEmpaque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDatos);
        if (tDatos.getColumnModel().getColumnCount() > 0) {
            tDatos.getColumnModel().getColumn(0).setResizable(false);
            tDatos.getColumnModel().getColumn(1).setResizable(false);
            tDatos.getColumnModel().getColumn(2).setResizable(false);
            tDatos.getColumnModel().getColumn(3).setResizable(false);
            tDatos.getColumnModel().getColumn(4).setResizable(false);
            tDatos.getColumnModel().getColumn(5).setResizable(false);
        }

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        tBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tBusquedaKeyTyped(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("idEmpaque");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("idProducto:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("idEmpaque:");

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        tNumPage.setText("0");

        bSiguiente.setText("Siguiente");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        cProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cProductos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cProductosItemStateChanged(evt);
            }
        });

        cEmpaque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cEmpaque.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cEmpaqueItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cProductos, 0, 141, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(chkEstatus)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(bGuardar))
                                        .addComponent(tPuntoReorden, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tPrecioVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tPrecioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(cEmpaque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(53, 53, 53)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNumPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSiguiente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(bBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tPuntoReorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cEmpaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEstatus)
                            .addComponent(bGuardar))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNumPage)
                    .addComponent(bSiguiente)
                    .addComponent(bAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstatusActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
       if(Integer.parseInt(this.tPrecioCompra.getText())<Integer.parseInt(this.tPrecioVenta.getText())){
            if(Integer.parseInt(this.tPuntoReorden.getText())>0){
                pr = new PresentacionesProducto();
        if (this.tPrecioCompra.getText().length() == 0 || this.tPrecioVenta.getText().length() == 0
                || this.tPuntoReorden.getText().length()== 0) {
            JOptionPane.showConfirmDialog(this, "No puede haber campos vacios","Campos vacios",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        } else {
            pr.setIdPresentacion(pdao.UltimoID());
            pr.setPrecioCompra(Float.parseFloat(this.tPrecioCompra.getText()));
            pr.setPrecioVenta(Float.parseFloat(this.tPrecioVenta.getText()));
            pr.setPuntoReorden(Float.parseFloat(this.tPuntoReorden.getText()));
            pr.setIdProducto(this.reg.get(proSelected).getId());
            pr.setIdEmpaque(this.regE.get(EmpSelected).getId());
            if (this.chkEstatus.isSelected()) {
                pr.setEstatus("A");
            } else {
                pr.setEstatus("I");
            }
            pdao.guardarPresentacionesProducto(pr);
            cargar();
            paginar();
            limpiar();
        }
            }else{
                JOptionPane.showConfirmDialog(this, "El punto de reorden debe ser mayor a 0","Error puto",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);

            }
       }else{
           JOptionPane.showConfirmDialog(this, "El precio de venta debe ser mayor que el precio de compra","Error de precios",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void tPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecioVentaActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        pdao.eliminarPresentacionesProducto(Integer.parseInt(this.tBusqueda.getText()));
        this.tDatos.setModel(pdao.cargarTabla(tDatos, pagina));
        noPaginas=pdao.cantPaginas();
        cargar();
        paginar();
        limpiar();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        this.tDatos.setModel(pdao.buscarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
        limpiar();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        if (edit) {
            edit = false;
            pr = new PresentacionesProducto();
            pr.setIdPresentacion(Integer.parseInt(this.tBusqueda.getText()));
            pr.setPrecioCompra(Float.parseFloat(this.tPrecioCompra.getText()));
            pr.setPrecioVenta(Float.parseFloat(this.tPrecioVenta.getText()));
            pr.setPuntoReorden(Float.parseFloat(this.tPuntoReorden.getText()));
            pr.setIdProducto(this.reg.get(proSelected).getId());
            pr.setIdEmpaque(this.regE.get(EmpSelected).getId());
            if (this.chkEstatus.isSelected()) {
                pr.setEstatus("A");
            } else {
                pr.setEstatus("I");
            }
            pdao.editarPresentacionesProducto(pr, pr.getIdPresentacion());
            cargar();
            limpiar();
        } else {
            edit = true;
            this.tDatos.setModel(pdao.buscarId(tDatos, Integer.parseInt(this.tBusqueda.getText())));
            pr = pdao.buscarIdEdicion(Integer.parseInt(this.tBusqueda.getText()));
            this.tPrecioCompra.setText(String.valueOf(pr.getPrecioCompra()));
            this.tPrecioVenta.setText(String.valueOf(pr.getPrecioVenta()));
            this.tPuntoReorden.setText(String.valueOf(pr.getPuntoReorden()));
            if (pr.getEstatus().equals("A")) {
                this.chkEstatus.setSelected(true);
            } else {
                this.chkEstatus.setSelected(false);
            }
            this.cProductos.setSelectedIndex(this.buscarPr(pr.getIdProducto()));
            this.cEmpaque.setSelectedIndex(this.buscarEm(pr.getIdEmpaque()));
        }
        this.bBuscar.setVisible(!edit);
        this.bEliminar.setVisible(!edit);
        this.bGuardar.setVisible(!edit);
    }//GEN-LAST:event_bEditarActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        if (pagina > 0)pagina--;
        paginar();
        cargar();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        // TODO add your handling code here:
        if (pagina < noPaginas)pagina++;
        paginar();
        cargar();
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void tBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBusquedaKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showConfirmDialog(this, "Caracter no valido","error",JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tBusquedaKeyTyped

    private void cProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cProductosItemStateChanged
        // TODO add your handling code here:
        this.proSelected=this.cProductos.getSelectedIndex();
    }//GEN-LAST:event_cProductosItemStateChanged

    private void tPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPrecioVentaKeyTyped
        
    }//GEN-LAST:event_tPrecioVentaKeyTyped

    private void cEmpaqueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cEmpaqueItemStateChanged
        this.EmpSelected=this.cEmpaque.getSelectedIndex();
    }//GEN-LAST:event_cEmpaqueItemStateChanged
    public void cargar() {
        this.tDatos.setModel(pdao.cargarTabla(tDatos,pagina));
        reg=new ArrayList();
        reg=pdao.consultarProd();
        cProductos.removeAllItems();
        for (int i = 0; i < reg.size(); i++) {
            this.cProductos.addItem(reg.get(i).getNombre());
        }
        regE=new ArrayList();
        regE=pdao.consultarEmp();
        cEmpaque.removeAllItems();
        for (int i = 0; i < regE.size(); i++) {
            this.cEmpaque.addItem(regE.get(i).getNombre());
        }
        this.repaint();
    }

    public void limpiar() {
        this.tPrecioCompra.setText("");
        this.tPrecioVenta.setText("");
        this.tPuntoReorden.setText("");
    }
    private int buscarPr(int id) {
        int idx = -1;
        for (int i = 0; i < reg.size(); i++) {
            if (reg.get(i).getId() == id) {
                return i;
            }
        }
        return idx;
    }
    private int buscarEm(int id) {
        int idx = -1;
        for (int i = 0; i < regE.size(); i++) {
            if (regE.get(i).getId() == id) {
                return i;
            }
        }
    return idx;
    }
    public void paginar() {
        if (pagina == 0) {
            this.bAtras.setVisible(false);
        } else {
            this.bAtras.setVisible(true);
        }
        if (pagina < noPaginas) {
            this.bSiguiente.setVisible(true);
        } else {
            this.bSiguiente.setVisible(false);
        }
        this.tNumPage.setText((pagina + 1) + " de " + (noPaginas + 1));
    }

    public void datoTabla() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JComboBox<String> cEmpaque;
    private javax.swing.JComboBox<String> cProductos;
    private javax.swing.JCheckBox chkEstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBusqueda;
    private javax.swing.JTable tDatos;
    private javax.swing.JLabel tNumPage;
    private javax.swing.JTextField tPrecioCompra;
    private javax.swing.JTextField tPrecioVenta;
    private javax.swing.JTextField tPuntoReorden;
    // End of variables declaration//GEN-END:variables
}
